package io.github.sehako.japda.ledger.infrastructure.persistence

import io.github.sehako.japda.ledger.application.dto.CreditWalletCommand
import io.github.sehako.japda.ledger.application.service.CreditWalletService
import io.github.sehako.japda.ledger.application.service.WalletBalanceOverflowException
import io.github.sehako.japda.ledger.domain.model.LedgerSourceType
import java.time.Clock
import java.time.Instant
import java.time.ZoneOffset
import java.util.concurrent.CountDownLatch
import java.util.concurrent.Executors
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.jdbc.datasource.DataSourceTransactionManager
import org.springframework.jdbc.datasource.DriverManagerDataSource
import org.springframework.transaction.support.TransactionTemplate
import org.testcontainers.junit.jupiter.Container
import org.testcontainers.junit.jupiter.Testcontainers
import org.testcontainers.postgresql.PostgreSQLContainer
import kotlin.test.assertEquals

@Testcontainers
@DisplayName("JDBC 지갑 원장 저장소")
class JdbcLedgerRepositoryIntegrationTest {
	private val dataSource by lazy {
		DriverManagerDataSource(postgres.jdbcUrl, postgres.username, postgres.password)
	}
	private val jdbcTemplate by lazy { JdbcTemplate(dataSource) }
	private val transactionTemplate by lazy { TransactionTemplate(DataSourceTransactionManager(dataSource)) }
	private val service by lazy {
		CreditWalletService(
			JdbcWalletRepository(jdbcTemplate),
			JdbcLedgerEntryRepository(jdbcTemplate),
			Clock.fixed(NOW, ZoneOffset.UTC),
		)
	}

	@BeforeEach
	fun 데이터_초기화() {
		jdbcTemplate.execute("DROP TABLE IF EXISTS ledger_entries")
		jdbcTemplate.execute("DROP TABLE IF EXISTS wallets")
		jdbcTemplate.execute(
			"""
			CREATE TABLE wallets (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				user_id BIGINT NOT NULL UNIQUE,
				balance BIGINT NOT NULL DEFAULT 0 CHECK (balance >= 0),
				created_at TIMESTAMP WITH TIME ZONE NOT NULL,
				updated_at TIMESTAMP WITH TIME ZONE NOT NULL
			)
			""".trimIndent(),
		)
		jdbcTemplate.execute(
			"""
			CREATE TABLE ledger_entries (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				wallet_id BIGINT NOT NULL REFERENCES wallets(id),
				direction VARCHAR(20) NOT NULL,
				amount BIGINT NOT NULL CHECK (amount > 0),
				balance_after BIGINT NOT NULL CHECK (balance_after >= 0),
				source_type VARCHAR(50) NOT NULL,
				source_id BIGINT NOT NULL CHECK (source_id > 0),
				created_at TIMESTAMP WITH TIME ZONE NOT NULL,
				UNIQUE (source_type, source_id)
			)
			""".trimIndent(),
		)
	}

	@Test
	@DisplayName("처음과 기존 지갑 입금은 잔액과 원장을 같은 트랜잭션에 누적한다")
	fun 처음과_기존_지갑_입금은_잔액과_원장을_같은_트랜잭션에_누적한다() {
		credit(userId = 10L, amount = 700L, sourceId = 1L)
		credit(userId = 10L, amount = 300L, sourceId = 2L)

		assertEquals(1, count("wallets"))
		assertEquals(1_000L, jdbcTemplate.queryForObject("SELECT balance FROM wallets WHERE user_id = 10", Long::class.java))
		assertEquals(listOf(700L, 1_000L), jdbcTemplate.queryForList("SELECT balance_after FROM ledger_entries ORDER BY id", Long::class.java))
	}

	@Test
	@DisplayName("동일 source 재호출은 잔액과 원장을 중복 반영하지 않는다")
	fun 동일_source_재호출은_잔액과_원장을_중복_반영하지_않는다() {
		credit(userId = 10L, amount = 700L, sourceId = 1L)

		val result = credit(userId = 10L, amount = 700L, sourceId = 1L)

		assertEquals(true, result.alreadyApplied)
		assertEquals(700L, jdbcTemplate.queryForObject("SELECT balance FROM wallets WHERE user_id = 10", Long::class.java))
		assertEquals(1, count("ledger_entries"))
	}

	@Test
	@DisplayName("동시 최초 입금은 지갑 하나에 두 원장을 직렬화한다")
	fun 동시_최초_입금은_지갑_하나에_두_원장을_직렬화한다() {
		val start = CountDownLatch(1)
		val executor = Executors.newFixedThreadPool(2)
		try {
			val futures = listOf(400L to 1L, 600L to 2L).map { (amount, sourceId) ->
				executor.submit {
					start.await()
					credit(userId = 10L, amount = amount, sourceId = sourceId)
				}
			}
			start.countDown()
			futures.forEach { it.get() }
		} finally {
			executor.shutdownNow()
		}

		assertEquals(1, count("wallets"))
		assertEquals(1_000L, jdbcTemplate.queryForObject("SELECT balance FROM wallets WHERE user_id = 10", Long::class.java))
		val balancesAfter = jdbcTemplate.queryForList("SELECT balance_after FROM ledger_entries ORDER BY balance_after", Long::class.java)
		assertEquals(2, balancesAfter.size)
		assertEquals(1_000L, balancesAfter.last())
		assertEquals(setOf(400L, 600L), jdbcTemplate.queryForList("SELECT amount FROM ledger_entries", Long::class.java).toSet())
	}

	@Test
	@DisplayName("잔액 overflow는 지갑 변경과 원장 생성을 rollback한다")
	fun 잔액_overflow는_지갑_변경과_원장_생성을_rollback한다() {
		jdbcTemplate.update(
			"INSERT INTO wallets (user_id, balance, created_at, updated_at) VALUES (10, ?, ?, ?)",
			Long.MAX_VALUE,
			NOW.atOffset(ZoneOffset.UTC),
			NOW.atOffset(ZoneOffset.UTC),
		)

		assertThrows<WalletBalanceOverflowException> { credit(userId = 10L, amount = 1L, sourceId = 1L) }

		assertEquals(Long.MAX_VALUE, jdbcTemplate.queryForObject("SELECT balance FROM wallets WHERE user_id = 10", Long::class.java))
		assertEquals(0, count("ledger_entries"))
	}

	private fun credit(userId: Long, amount: Long, sourceId: Long) = transactionTemplate.execute {
		service.credit(CreditWalletCommand(userId, amount, LedgerSourceType.SELLER_SETTLEMENT, sourceId))
	}

	private fun count(table: String): Int = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM $table", Int::class.java)!!

	private companion object {
		val NOW: Instant = Instant.parse("2026-09-16T00:00:00Z")

		@Container
		@JvmStatic
		val postgres = PostgreSQLContainer("postgres:18-alpine")
	}
}
