spring:
  application:
    name: batch
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/japda}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  flyway:
    enabled: false
  batch:
    jdbc:
      initialize-schema: never
