spring:
  application:
    name: batch
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/japda}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    hikari:
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE:12}
  flyway:
    enabled: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

japda:
  batch:
    daily-seller-settlement:
      worker-count: ${DAILY_SELLER_SETTLEMENT_WORKER_COUNT:8}
      collection-partition-count: ${DAILY_SELLER_SETTLEMENT_COLLECTION_PARTITION_COUNT:64}
      credit-partition-count: ${DAILY_SELLER_SETTLEMENT_CREDIT_PARTITION_COUNT:64}
