CREATE TABLE settlement_runs
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_date             DATE                     NOT NULL,
    platform_fee_rate_bps       INTEGER                  NOT NULL,
    status                      VARCHAR(30)              NOT NULL,
    collected_count             BIGINT                   NOT NULL DEFAULT 0,
    collected_amount            BIGINT                   NOT NULL DEFAULT 0,
    started_at                  TIMESTAMP WITH TIME ZONE NOT NULL,
    collection_completed_at     TIMESTAMP WITH TIME ZONE,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT settlement_runs_settlement_date_unique UNIQUE (settlement_date),
    CONSTRAINT settlement_runs_platform_fee_rate_bps_range CHECK (
        platform_fee_rate_bps >= 0 AND platform_fee_rate_bps <= 10000
    ),
    CONSTRAINT settlement_runs_status_valid CHECK (status IN ('COLLECTING', 'COLLECTED')),
    CONSTRAINT settlement_runs_collected_count_non_negative CHECK (collected_count >= 0),
    CONSTRAINT settlement_runs_collected_amount_non_negative CHECK (collected_amount >= 0)
);

CREATE TABLE settlement_details
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_run_id       BIGINT                   NOT NULL,
    payment_id              BIGINT                   NOT NULL,
    order_id                BIGINT                   NOT NULL,
    sale_id                 BIGINT                   NOT NULL,
    seller_id               BIGINT                   NOT NULL,
    recipient_user_id       BIGINT                   NOT NULL,
    quantity                INTEGER                  NOT NULL,
    unit_price              BIGINT                   NOT NULL,
    gross_amount            BIGINT                   NOT NULL,
    payment_approved_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT settlement_details_settlement_run_fk FOREIGN KEY (settlement_run_id) REFERENCES settlement_runs (id),
    CONSTRAINT settlement_details_payment_fk FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT settlement_details_order_fk FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT settlement_details_sale_fk FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT settlement_details_recipient_user_fk FOREIGN KEY (recipient_user_id) REFERENCES users (id),
    CONSTRAINT settlement_details_payment_unique UNIQUE (payment_id),
    CONSTRAINT settlement_details_seller_id_positive CHECK (seller_id > 0),
    CONSTRAINT settlement_details_quantity_positive CHECK (quantity > 0),
    CONSTRAINT settlement_details_unit_price_positive CHECK (unit_price > 0),
    CONSTRAINT settlement_details_gross_amount_positive CHECK (gross_amount > 0)
);

CREATE INDEX settlement_details_run_id_id_idx ON settlement_details (settlement_run_id, id);
