ALTER TABLE settlement_runs
    ADD COLUMN confirmation_completed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE settlement_runs
    DROP CONSTRAINT settlement_runs_status_valid,
    ADD CONSTRAINT settlement_runs_status_valid CHECK (status IN ('COLLECTING', 'COLLECTED', 'CONFIRMED'));

CREATE TABLE seller_settlements
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_run_id       BIGINT                   NOT NULL,
    seller_id               BIGINT                   NOT NULL,
    recipient_user_id       BIGINT                   NOT NULL,
    detail_count            BIGINT                   NOT NULL,
    gross_amount            BIGINT                   NOT NULL,
    platform_fee_amount     BIGINT                   NOT NULL,
    net_amount              BIGINT                   NOT NULL,
    status                  VARCHAR(30)              NOT NULL,
    confirmed_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT seller_settlements_run_fk FOREIGN KEY (settlement_run_id) REFERENCES settlement_runs (id),
    CONSTRAINT seller_settlements_recipient_user_fk FOREIGN KEY (recipient_user_id) REFERENCES users (id),
    CONSTRAINT seller_settlements_run_seller_unique UNIQUE (settlement_run_id, seller_id),
    CONSTRAINT seller_settlements_seller_id_positive CHECK (seller_id > 0),
    CONSTRAINT seller_settlements_detail_count_positive CHECK (detail_count > 0),
    CONSTRAINT seller_settlements_gross_amount_positive CHECK (gross_amount > 0),
    CONSTRAINT seller_settlements_platform_fee_amount_non_negative CHECK (platform_fee_amount >= 0),
    CONSTRAINT seller_settlements_net_amount_non_negative CHECK (net_amount >= 0),
    CONSTRAINT seller_settlements_status_valid CHECK (status = 'CONFIRMED'),
    CONSTRAINT seller_settlements_amounts_consistent CHECK (gross_amount = platform_fee_amount + net_amount)
);

CREATE INDEX seller_settlements_run_id_id_idx ON seller_settlements (settlement_run_id, id);
