CREATE TABLE wallets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL,
    balance     BIGINT                   NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT wallets_user_fk FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT wallets_user_id_unique UNIQUE (user_id),
    CONSTRAINT wallets_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE ledger_entries
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id       BIGINT                   NOT NULL,
    direction       VARCHAR(20)              NOT NULL,
    amount          BIGINT                   NOT NULL,
    balance_after   BIGINT                   NOT NULL,
    source_type     VARCHAR(50)              NOT NULL,
    source_id       BIGINT                   NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ledger_entries_wallet_fk FOREIGN KEY (wallet_id) REFERENCES wallets (id),
    CONSTRAINT ledger_entries_source_unique UNIQUE (source_type, source_id),
    CONSTRAINT ledger_entries_direction_valid CHECK (direction IN ('CREDIT', 'DEBIT')),
    CONSTRAINT ledger_entries_amount_positive CHECK (amount > 0),
    CONSTRAINT ledger_entries_balance_after_non_negative CHECK (balance_after >= 0),
    CONSTRAINT ledger_entries_source_type_valid CHECK (source_type = 'SELLER_SETTLEMENT'),
    CONSTRAINT ledger_entries_source_id_positive CHECK (source_id > 0),
    CONSTRAINT ledger_entries_seller_settlement_credit CHECK (
        source_type <> 'SELLER_SETTLEMENT' OR direction = 'CREDIT'
    )
);

CREATE INDEX ledger_entries_wallet_id_id_idx ON ledger_entries (wallet_id, id);

ALTER TABLE seller_settlements
    ADD COLUMN credited_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE seller_settlements
    DROP CONSTRAINT seller_settlements_status_valid,
    ADD CONSTRAINT seller_settlements_status_valid CHECK (status IN ('CONFIRMED', 'CREDITED')),
    ADD CONSTRAINT seller_settlements_credit_status_time_consistent CHECK (
        (status = 'CONFIRMED' AND credited_at IS NULL)
        OR (status = 'CREDITED' AND credited_at IS NOT NULL)
    );

ALTER TABLE settlement_runs
    ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE settlement_runs
    DROP CONSTRAINT settlement_runs_status_valid,
    ADD CONSTRAINT settlement_runs_status_valid CHECK (
        status IN ('COLLECTING', 'COLLECTED', 'CONFIRMED', 'COMPLETED')
    ),
    ADD CONSTRAINT settlement_runs_completion_status_time_consistent CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
        OR (status <> 'COMPLETED' AND completed_at IS NULL)
    );
