CREATE TABLE settlement_entries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id          BIGINT                   NOT NULL,
    order_id            BIGINT                   NOT NULL,
    sale_id             BIGINT                   NOT NULL,
    seller_id           BIGINT                   NOT NULL,
    recipient_user_id   BIGINT                   NOT NULL,
    quantity            INTEGER                  NOT NULL,
    unit_price          BIGINT                   NOT NULL,
    gross_amount        BIGINT                   NOT NULL,
    payment_approved_at TIMESTAMP WITH TIME ZONE NOT NULL,
    settlement_date     DATE                     NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT settlement_entries_payment_fk FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT settlement_entries_order_fk FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT settlement_entries_sale_fk FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT settlement_entries_recipient_user_fk FOREIGN KEY (recipient_user_id) REFERENCES users (id),
    CONSTRAINT settlement_entries_payment_unique UNIQUE (payment_id),
    CONSTRAINT settlement_entries_seller_id_positive CHECK (seller_id > 0),
    CONSTRAINT settlement_entries_quantity_positive CHECK (quantity > 0),
    CONSTRAINT settlement_entries_unit_price_positive CHECK (unit_price > 0),
    CONSTRAINT settlement_entries_gross_amount_positive CHECK (gross_amount > 0),
    CONSTRAINT settlement_entries_gross_amount_matches_quantity_and_unit_price CHECK (gross_amount = quantity * unit_price)
);

CREATE INDEX settlement_entries_settlement_date_id_idx ON settlement_entries (settlement_date, id);
