CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   BIGINT        NOT NULL,
    name        VARCHAR(100)  NOT NULL,
    description VARCHAR(3000),
    status      VARCHAR(20)   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT products_seller_id_positive CHECK (seller_id > 0),
    CONSTRAINT products_name_length CHECK (char_length(btrim(name)) BETWEEN 1 AND 100),
    CONSTRAINT products_description_length CHECK (
        description IS NULL OR char_length(btrim(description)) BETWEEN 1 AND 3000
    ),
    CONSTRAINT products_status CHECK (status IN ('DRAFT'))
);
