CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   BIGINT                   NOT NULL,
    name        VARCHAR(100)             NOT NULL,
    description VARCHAR(5000)            NOT NULL,
    status      VARCHAR(20)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_products_seller_id CHECK (seller_id > 0),
    CONSTRAINT chk_products_name_length CHECK (char_length(name) BETWEEN 1 AND 100),
    CONSTRAINT chk_products_description_length CHECK (char_length(description) BETWEEN 1 AND 5000),
    CONSTRAINT chk_products_status CHECK (status IN ('DRAFT', 'READY'))
);
