ALTER TABLE products DROP CONSTRAINT products_status;
ALTER TABLE products
    ADD CONSTRAINT products_status CHECK (status IN ('DRAFT', 'READY'));

CREATE TABLE product_images
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT                   NOT NULL,
    object_key        VARCHAR(500)             NOT NULL,
    content_type      VARCHAR(20)              NOT NULL,
    size_bytes        BIGINT                   NOT NULL,
    display_order     INTEGER                  NOT NULL,
    is_representative BOOLEAN                  NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT product_images_product_fk FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT product_images_object_key_unique UNIQUE (object_key),
    CONSTRAINT product_images_content_type CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT product_images_size_bytes CHECK (size_bytes BETWEEN 1 AND 10485760),
    CONSTRAINT product_images_display_order CHECK (display_order BETWEEN 0 AND 9),
    CONSTRAINT product_images_product_display_order_unique UNIQUE (product_id, display_order)
);

CREATE UNIQUE INDEX product_images_one_representative_per_product
    ON product_images (product_id)
    WHERE is_representative;
