CREATE TABLE product_images
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT                   NOT NULL,
    object_key        TEXT                     NOT NULL,
    content_type      VARCHAR(20)              NOT NULL,
    size_bytes        BIGINT                   NOT NULL,
    sort_order        INTEGER                  NOT NULL,
    is_representative BOOLEAN                  NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_product_images_object_key UNIQUE (object_key),
    CONSTRAINT uk_product_images_product_sort_order UNIQUE (product_id, sort_order),
    CONSTRAINT chk_product_images_size_bytes CHECK (size_bytes BETWEEN 1 AND 10485760),
    CONSTRAINT chk_product_images_sort_order CHECK (sort_order BETWEEN 0 AND 9),
    CONSTRAINT chk_product_images_content_type CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp'))
);

CREATE UNIQUE INDEX uk_product_images_representative
    ON product_images (product_id)
    WHERE is_representative = TRUE;
