CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE sales
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT                   NOT NULL,
    price              BIGINT                   NOT NULL,
    initial_quantity   BIGINT                   NOT NULL,
    remaining_quantity BIGINT                   NOT NULL,
    starts_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sales_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_sales_price CHECK (price >= 1),
    CONSTRAINT chk_sales_initial_quantity CHECK (initial_quantity >= 1),
    CONSTRAINT chk_sales_remaining_quantity CHECK (
        remaining_quantity BETWEEN 0 AND initial_quantity
    ),
    CONSTRAINT chk_sales_period CHECK (ends_at > starts_at),
    CONSTRAINT ex_sales_product_period EXCLUDE USING gist (
        product_id WITH =,
        (tstzrange(starts_at, ends_at, '[)')) WITH &&
    )
);
