CREATE TABLE sale_days
(
    sale_date        DATE PRIMARY KEY,
    capacity         INTEGER NOT NULL,
    registered_count INTEGER NOT NULL,
    CONSTRAINT sale_days_capacity_positive CHECK (capacity > 0),
    CONSTRAINT sale_days_registered_count_range CHECK (
        registered_count >= 0 AND registered_count <= capacity
    )
);

CREATE TABLE sales
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT                   NOT NULL,
    seller_id  BIGINT                   NOT NULL,
    sale_date  DATE                     NOT NULL,
    price      BIGINT                   NOT NULL,
    quantity   INTEGER                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT sales_product_fk FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT sales_sale_day_fk FOREIGN KEY (sale_date) REFERENCES sale_days (sale_date),
    CONSTRAINT sales_seller_id_positive CHECK (seller_id > 0),
    CONSTRAINT sales_price_positive CHECK (price > 0),
    CONSTRAINT sales_quantity_positive CHECK (quantity > 0),
    CONSTRAINT sales_seller_sale_date_unique UNIQUE (seller_id, sale_date)
);
