CREATE TABLE orders
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id          BIGINT                   NOT NULL,
    buyer_id         BIGINT                   NOT NULL,
    idempotency_key  UUID                     NOT NULL,
    quantity         INTEGER                  NOT NULL,
    product_name     VARCHAR(100)             NOT NULL,
    unit_price       BIGINT                   NOT NULL,
    total_price      BIGINT                   NOT NULL,
    status           VARCHAR(30)              NOT NULL,
    recipient_name   VARCHAR(100)             NOT NULL,
    phone_number     VARCHAR(30)              NOT NULL,
    postal_code      VARCHAR(20)              NOT NULL,
    address          VARCHAR(255)             NOT NULL,
    detail_address   VARCHAR(255)             NOT NULL,
    delivery_message VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT orders_sale_fk FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT orders_buyer_id_positive CHECK (buyer_id > 0),
    CONSTRAINT orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT orders_product_name_not_blank CHECK (char_length(btrim(product_name)) > 0),
    CONSTRAINT orders_unit_price_positive CHECK (unit_price > 0),
    CONSTRAINT orders_total_price_positive CHECK (total_price > 0),
    CONSTRAINT orders_status_valid CHECK (status IN ('PENDING_PAYMENT')),
    CONSTRAINT orders_recipient_name_not_blank CHECK (char_length(btrim(recipient_name)) > 0),
    CONSTRAINT orders_phone_number_not_blank CHECK (char_length(btrim(phone_number)) > 0),
    CONSTRAINT orders_postal_code_not_blank CHECK (char_length(btrim(postal_code)) > 0),
    CONSTRAINT orders_address_not_blank CHECK (char_length(btrim(address)) > 0),
    CONSTRAINT orders_detail_address_not_blank CHECK (char_length(btrim(detail_address)) > 0),
    CONSTRAINT orders_expires_after_creation CHECK (expires_at > created_at),
    CONSTRAINT orders_buyer_id_idempotency_key_unique UNIQUE (buyer_id, idempotency_key)
);

CREATE INDEX orders_active_reservation_idx
    ON orders (sale_id, expires_at)
    WHERE status = 'PENDING_PAYMENT';
