CREATE TABLE buyer_shipping_address_books
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id   BIGINT                   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT buyer_shipping_address_books_buyer_id_positive CHECK (buyer_id > 0),
    CONSTRAINT buyer_shipping_address_books_buyer_id_unique UNIQUE (buyer_id)
);

CREATE TABLE buyer_shipping_addresses
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_shipping_address_book_id BIGINT                   NOT NULL,
    address_name                   VARCHAR(100)             NOT NULL,
    recipient_name                 VARCHAR(100)             NOT NULL,
    phone_number                   VARCHAR(30)              NOT NULL,
    postal_code                    VARCHAR(20)              NOT NULL,
    address                        VARCHAR(255)             NOT NULL,
    detail_address                 VARCHAR(255)             NOT NULL,
    delivery_message               VARCHAR(500),
    created_at                     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT buyer_shipping_addresses_book_fk
        FOREIGN KEY (buyer_shipping_address_book_id) REFERENCES buyer_shipping_address_books (id),
    CONSTRAINT buyer_shipping_addresses_address_name_not_blank CHECK (char_length(btrim(address_name)) > 0),
    CONSTRAINT buyer_shipping_addresses_recipient_name_not_blank CHECK (char_length(btrim(recipient_name)) > 0),
    CONSTRAINT buyer_shipping_addresses_phone_number_not_blank CHECK (char_length(btrim(phone_number)) > 0),
    CONSTRAINT buyer_shipping_addresses_postal_code_not_blank CHECK (char_length(btrim(postal_code)) > 0),
    CONSTRAINT buyer_shipping_addresses_address_not_blank CHECK (char_length(btrim(address)) > 0),
    CONSTRAINT buyer_shipping_addresses_detail_address_not_blank CHECK (char_length(btrim(detail_address)) > 0),
    CONSTRAINT buyer_shipping_addresses_book_id_address_name_unique
        UNIQUE (buyer_shipping_address_book_id, address_name)
);
