ALTER TABLE orders DROP CONSTRAINT orders_status_valid;
ALTER TABLE orders ADD CONSTRAINT orders_status_valid CHECK (status IN ('PENDING_PAYMENT', 'PAID'));

CREATE TABLE payments
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id             BIGINT                   NOT NULL,
    payment_key          VARCHAR(200)             NOT NULL,
    toss_idempotency_key VARCHAR(36)              NOT NULL,
    status               VARCHAR(30)              NOT NULL,
    requested_amount     BIGINT                   NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    first_requested_at   TIMESTAMP WITH TIME ZONE,
    last_checked_at      TIMESTAMP WITH TIME ZONE,
    next_reconcile_at    TIMESTAMP WITH TIME ZONE,
    approved_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT payments_order_fk FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT payments_order_unique UNIQUE (order_id),
    CONSTRAINT payments_payment_key_unique UNIQUE (payment_key),
    CONSTRAINT payments_toss_idempotency_key_unique UNIQUE (toss_idempotency_key),
    CONSTRAINT payments_requested_amount_positive CHECK (requested_amount > 0),
    CONSTRAINT payments_payment_key_not_blank CHECK (char_length(btrim(payment_key)) > 0),
    CONSTRAINT payments_status_valid CHECK (status IN ('CONFIRMING', 'APPROVED', 'FAILED', 'REVIEW_REQUIRED'))
);

CREATE INDEX payments_reconcile_idx ON payments (status, next_reconcile_at, id);
CREATE INDEX orders_paid_sale_idx ON orders (sale_id) WHERE status = 'PAID';
