CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider         VARCHAR(20)              NOT NULL,
    provider_subject VARCHAR(255)             NOT NULL,
    email            VARCHAR(320)             NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT users_provider_subject_unique UNIQUE (provider, provider_subject),
    CONSTRAINT users_provider_valid CHECK (provider = 'GOOGLE')
);

CREATE TABLE user_roles
(
    user_id BIGINT      NOT NULL,
    role    VARCHAR(20) NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT user_roles_role_valid CHECK (role IN ('BUYER', 'ADMIN'))
);
