package io.github.sehako.japda.batch.settlement.exception

enum class SettlementConfirmationErrorType {
	RUN_NOT_FOUND,
	INVALID_RUN_STATUS,
	DETAIL_AGGREGATE_MISMATCH,
	RECIPIENT_MISMATCH,
	AMOUNT_OUT_OF_RANGE,
	EXISTING_RESULT,
	SAVED_RESULT_DETAIL_MISMATCH,
	SAVED_RESULT_AGGREGATE_MISMATCH,
	SAVED_RESULT_FORMULA_MISMATCH,
	CONFIRMED_RESULT_MISMATCH,
	STATE_TRANSITION_FAILED,
}
