= Japda 백엔드 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 판매자 상품 기본 정보 등록

=== 성공

operation::product-create[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']

=== 상품명 누락

operation::product-create-name-required[snippets='http-request,http-response,response-fields']

== 판매자 판매 준비 완료 상품 목록 조회

=== 성공

operation::product-ready-list[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== 지원하지 않는 정렬 방식

operation::product-ready-list-sort-invalid[snippets='http-request,http-response,response-fields']

== 판매자 상품 이미지 최초 등록

=== 성공

operation::product-image-register[snippets='http-request,request-headers,path-parameters,request-parts,http-response,response-fields']

=== 대표 이미지 지정 오류

operation::product-image-register-representative-invalid[snippets='http-request,http-response,response-fields']

== 판매자 판매 일정 등록

=== 성공

operation::sale-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 판매일 정원 초과

operation::sale-create-capacity-exceeded[snippets='http-request,http-response,response-fields']

=== 판매일 누락

operation::sale-create-date-required[snippets='http-request,http-response,response-fields']

== 구매자 판매 상품 목록 조회

=== 성공

operation::buyer-sale-product-list[snippets='http-request,query-parameters,http-response,response-fields']

=== 빈 목록

operation::buyer-sale-product-list-empty[snippets='http-request,query-parameters,http-response,response-fields']

=== 요청 파라미터 오류

operation::buyer-sale-product-list-parameter-invalid[snippets='http-request,http-response,response-fields']

=== 판매일 조회 범위 초과

operation::buyer-sale-product-list-date-out-of-range[snippets='http-request,http-response,response-fields']

== 구매자 판매 상품 상세 조회

=== 성공

operation::buyer-sale-product-detail[snippets='http-request,path-parameters,http-response,response-fields']

=== 판매 일정 식별자 오류

operation::buyer-sale-product-detail-id-invalid[snippets='http-request,http-response,response-fields']

=== 판매 상품 없음

operation::buyer-sale-product-detail-not-found[snippets='http-request,http-response,response-fields']
