= Japda 백엔드 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 판매자 상품 기본 정보 등록

=== 성공

operation::product-create[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']

=== 상품명 누락

operation::product-create-name-required[snippets='http-request,http-response,response-fields']

== 판매자 상품 이미지 최초 등록

=== 성공

operation::product-image-register[snippets='http-request,request-headers,path-parameters,request-parts,http-response,response-fields']

=== 대표 이미지 지정 오류

operation::product-image-register-representative-invalid[snippets='http-request,http-response,response-fields']

== 판매자 판매 일정 등록

=== 성공

operation::sale-create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 판매일 정원 초과

operation::sale-create-capacity-exceeded[snippets='http-request,http-response,response-fields']

=== 판매일 누락

operation::sale-create-date-required[snippets='http-request,http-response,response-fields']
